<?php
/**
 * BuildTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Drone API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DroneClient;

/**
 * BuildTest Class Doc Comment
 *
 * @category    Class */
// * @description A build for a repository.
/**
 * @package     DroneClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuildTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Build"
     */
    public function testBuild()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "enqueued_at"
     */
    public function testPropertyEnqueuedAt()
    {
    }

    /**
     * Test attribute "started_at"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "finished_at"
     */
    public function testPropertyFinishedAt()
    {
    }

    /**
     * Test attribute "deploy_to"
     */
    public function testPropertyDeployTo()
    {
    }

    /**
     * Test attribute "commit"
     */
    public function testPropertyCommit()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "ref"
     */
    public function testPropertyRef()
    {
    }

    /**
     * Test attribute "refspec"
     */
    public function testPropertyRefspec()
    {
    }

    /**
     * Test attribute "remote"
     */
    public function testPropertyRemote()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "author_avatar"
     */
    public function testPropertyAuthorAvatar()
    {
    }

    /**
     * Test attribute "author_email"
     */
    public function testPropertyAuthorEmail()
    {
    }

    /**
     * Test attribute "link_url"
     */
    public function testPropertyLinkUrl()
    {
    }

    /**
     * Test attribute "jobs"
     */
    public function testPropertyJobs()
    {
    }
}
