<?php
/**
 * BuildsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Drone API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DroneClient;

use \DroneClient\Configuration;
use \DroneClient\ApiException;
use \DroneClient\ObjectSerializer;

/**
 * BuildsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuildsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for reposOwnerNameBuildsGet
     *
     * Get recent builds.
     *
     */
    public function testReposOwnerNameBuildsGet()
    {
    }

    /**
     * Test case for reposOwnerNameBuildsNumberGet
     *
     * Get the latest build.
     *
     */
    public function testReposOwnerNameBuildsNumberGet()
    {
    }

    /**
     * Test case for reposOwnerNameBuildsNumberPost
     *
     * Restart a build.
     *
     */
    public function testReposOwnerNameBuildsNumberPost()
    {
    }

    /**
     * Test case for reposOwnerNameLogsNumberJobDelete
     *
     * Cancel a Job.
     *
     */
    public function testReposOwnerNameLogsNumberJobDelete()
    {
    }

    /**
     * Test case for reposOwnerNameLogsNumberJobGet
     *
     * Get build logs.
     *
     */
    public function testReposOwnerNameLogsNumberJobGet()
    {
    }
}
