<?php
/**
 * ReposApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Drone API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DroneClient;

use \DroneClient\Configuration;
use \DroneClient\ApiException;
use \DroneClient\ObjectSerializer;

/**
 * ReposApiTest Class Doc Comment
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReposApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for reposOwnerNameDelete
     *
     * Delete a repo.
     *
     */
    public function testReposOwnerNameDelete()
    {
    }

    /**
     * Test case for reposOwnerNameEncryptPost
     *
     * Encrypt repo secrets.
     *
     */
    public function testReposOwnerNameEncryptPost()
    {
    }

    /**
     * Test case for reposOwnerNameGet
     *
     * Get a repo.
     *
     */
    public function testReposOwnerNameGet()
    {
    }

    /**
     * Test case for reposOwnerNamePatch
     *
     * Updates a repo.
     *
     */
    public function testReposOwnerNamePatch()
    {
    }

    /**
     * Test case for reposOwnerNamePost
     *
     * Activates a repo.
     *
     */
    public function testReposOwnerNamePost()
    {
    }
}
