<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Drone API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DroneClient;

use \DroneClient\Configuration;
use \DroneClient\ApiException;
use \DroneClient\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  DroneClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for usersGet
     *
     * Get all users.
     *
     */
    public function testUsersGet()
    {
    }

    /**
     * Test case for usersLoginDelete
     *
     * Delete a user.
     *
     */
    public function testUsersLoginDelete()
    {
    }

    /**
     * Test case for usersLoginGet
     *
     * Get a user.
     *
     */
    public function testUsersLoginGet()
    {
    }

    /**
     * Test case for usersLoginPatch
     *
     * Update a user.
     *
     */
    public function testUsersLoginPatch()
    {
    }

    /**
     * Test case for usersLoginPost
     *
     * Create a user.
     *
     */
    public function testUsersLoginPost()
    {
    }
}
